apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
spec:
  containers:
    - name: kafka-producer
      image: jorgesanchezl/opensource-datalake-producer:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
  restartPolicy: Never
