apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-sidecar-scripts
data:
  init-nifi.sh: |
    #!/bin/sh
    set -e

    NIFI_API="http://nifi:8080/nifi-api"
    TEMPLATE_NAME="nifi"
    PROCESSOR_NAME="PutS3Object"

    apk add --no-cache curl jq

    echo "Waiting for NiFi to be ready..."
    until curl -s "$NIFI_API/flow/status" > /dev/null; do
      sleep 5
    done
    echo "NiFi is ready."

    echo "Uploading template..."
    curl -s -X POST \
      -H "Content-Type: multipart/form-data" \
      -F "template=@/template.xml" \
      "$NIFI_API/process-groups/root/templates/upload"

    ROOT_PG_ID=$(curl -s "$NIFI_API/flow/process-groups/root" | jq -r '.processGroupFlow.id')

    echo "Searching template ID for template named '$TEMPLATE_NAME'..."
    TEMPLATE_ID=$(curl -s "$NIFI_API/flow/templates" | jq -r --arg NAME "$TEMPLATE_NAME" '.templates[] | select(.template.name == $NAME) | .template.id')

    if [ -z "$TEMPLATE_ID" ]; then
      echo "Error: Could not find template '$TEMPLATE_NAME'"
      exit 1
    fi

    echo "Posting template $TEMPLATE_ID..."
    curl -s -X POST -H "Content-Type: application/json" \
      -d "{\"templateId\":\"$TEMPLATE_ID\",\"originX\":0.0,\"originY\":0.0}" \
      "$NIFI_API/process-groups/$ROOT_PG_ID/template-instance"

    echo "Waiting 5 seconds for template instantiation..."
    sleep 5

    echo "Starting processors in group $ROOT_PG_ID..."

    curl -s -X PUT -H "Content-Type: application/json" \
      -d '{
        "id": "'"$ROOT_PG_ID"'",
        "state": "RUNNING"
      }' "$NIFI_API/flow/process-groups/$ROOT_PG_ID"

    
    echo "NiFi configured correctly!"
    tail -f /dev/null